// seedMenuData.js - TO'LIQ VERSIYA (Barcha ichimliklar qo'shilgan)
// Barcha ovqatlar va ichimliklar, jumladan kofe, choy, kokteyllar va boshqalar

import { dbSet } from "./firebase";

// ─── HELPERS ──────────────────────────────────────────────────────────────────
const uid = () => Math.random().toString(36).slice(2, 9);
const today = () => new Date().toISOString().slice(0, 10);

// ─── CATEGORIES ──────────────────────────────────────────────────────────────
const CATEGORIES = {
  // OVQATLAR
  bread: {
    id: "cat_bread",
    name: "Nonlar",
    icon: "🥖",
    color: "#d4a373",
    status: "active",
    createdAt: today(),
  },
  salads: {
    id: "cat_salads",
    name: "Salatlar",
    icon: "🥗",
    color: "#2ecc71",
    status: "active",
    createdAt: today(),
  },
  soups: {
    id: "cat_soups",
    name: "Sho'rvalar",
    icon: "🍜",
    color: "#e67e22",
    status: "active",
    createdAt: today(),
  },
  italian: {
    id: "cat_italian",
    name: "Italyan taomlari",
    icon: "🍝",
    color: "#e74c3c",
    status: "active",
    createdAt: today(),
  },
  pizza: {
    id: "cat_pizza",
    name: "Pitsa",
    icon: "🍕",
    color: "#e74c3c",
    status: "active",
    createdAt: today(),
  },
  steaks: {
    id: "cat_steaks",
    name: "Steykler",
    icon: "🥩",
    color: "#8e44ad",
    status: "active",
    createdAt: today(),
  },
  grill: {
    id: "cat_grill",
    name: "Mangal",
    icon: "🔥",
    color: "#d35400",
    status: "active",
    createdAt: today(),
  },
  sauces: {
    id: "cat_sauces",
    name: "Souslar",
    icon: "🧂",
    color: "#f39c12",
    status: "active",
    createdAt: today(),
  },
  cold_snacks: {
    id: "cat_cold_snacks",
    name: "Sovuq appetitlar",
    icon: "🧀",
    color: "#3498db",
    status: "active",
    createdAt: today(),
  },
  custom: {
    id: "cat_custom",
    name: "Buyurtma taomlar",
    icon: "👨‍🍳",
    color: "#9b59b6",
    status: "active",
    createdAt: today(),
  },
  turkish: {
    id: "cat_turkish",
    name: "Turk taomlari",
    icon: "🥙",
    color: "#f39c12",
    status: "active",
    createdAt: today(),
  },
  hot: {
    id: "cat_hot",
    name: "Issiq taomlar",
    icon: "🍖",
    color: "#c0392b",
    status: "active",
    createdAt: today(),
  },
  // ICHIMLIKLAR
  coffee: {
    id: "cat_coffee",
    name: "Kofe",
    icon: "☕",
    color: "#6f4e37",
    status: "active",
    createdAt: today(),
  },
  tea: {
    id: "cat_tea",
    name: "Choy",
    icon: "🍵",
    color: "#4a7a40",
    status: "active",
    createdAt: today(),
  },
  lemonade: {
    id: "cat_lemonade",
    name: "Limonalar",
    icon: "🍋",
    color: "#f1c40f",
    status: "active",
    createdAt: today(),
  },
  cocktails: {
    id: "cat_cocktails",
    name: "Kokteyllar",
    icon: "🍹",
    color: "#e67e22",
    status: "active",
    createdAt: today(),
  },
  milkshake: {
    id: "cat_milkshake",
    name: "Milk-shkeyklar",
    icon: "🥤",
    color: "#f39c12",
    status: "active",
    createdAt: today(),
  },
  fresh: {
    id: "cat_fresh",
    name: "Fresh va Smoothie",
    icon: "🧃",
    color: "#2ecc71",
    status: "active",
    createdAt: today(),
  },
  cold_drinks: {
    id: "cat_cold_drinks",
    name: "Sovuq ichimliklar",
    icon: "🥤",
    color: "#3498db",
    status: "active",
    createdAt: today(),
  },
};

// ─── OVQATLAR ────────────────────────────────────────────────────────────────

// ─── 1. NONLAR (BREAD) ─────────────────────────────────────────────────────
const breadItems = [
  {
    name: "Сырный Хлеб",
    description: "170 гр. Mazali pishloqli non",
    price: 14000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🧀",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Лепешки",
    description: "100 гр. Tortillas - yupqa non",
    price: 5000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🫓",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Ливанский хлеб",
    description: "130 гр. Lebanese bread - Livan noni",
    price: 6000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🥙",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Булочка с маком",
    description: "Ko'knorli bulochka",
    price: 6000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🥯",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Грисини",
    description: "Grissini - italyan tayoqchasi",
    price: 3000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🥖",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Французкий багет",
    description: "Fransuz bageti",
    price: 9000,
    category: "cat_bread",
    categoryType: "food",
    emoji: "🥖",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
];

// ─── 2. SALATLAR (SALADS) ──────────────────────────────────────────────────
const saladItems = [
  {
    name: "Нежный",
    description: "Отварная говядина, свежие огурцы, свежие помидоры, сыр Гауда, микс салата",
    price: 55000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥗",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Японский",
    description: "Свежие огурцы, свежие помидоры, болгарский микс, отварная говядина, микс салата, соевый соус",
    price: 55000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥗",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мексиканский",
    description: "220 гр. Говядина, кукуруза, маринованные грибы, болгарский светофор, красный лук",
    price: 70000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🌮",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Греческий",
    description: "Свежие огурцы, свежие помидоры, болгарский микс, фетакса, айсберг",
    price: 55000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🇬🇷",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Гнездо глухаря",
    description: "Белокочанная капуста, свежие огурцы, кукуруза, майонез, запеченное куриное филе, перепелиное яйцо",
    price: 40000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥚",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Цезарь с курицей",
    description: "Айсберг, куриное филе, соус Цезарь, гренки, помидоры черри, сыр Пармезан",
    price: 55000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥗",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Апельсин в ореховом соусе",
    description: "320 гр. Апельсин, огурец, куриное филе, ореховый соус, греческий орех",
    price: 50000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🍊",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Оливые с ростбифом",
    description: "Ростбиф, зеленый горошек, отварной картофель, отварная морковь, яйца, майонез",
    price: 75000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥔",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мужской каприз",
    description: "Колбаса копченая, говядина копченая, язык отварной, сыр моцарелла, майонез",
    price: 65000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🧆",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Ростбиф с запеченными овощами",
    description: "Ростбиф, запеченные баклажаны, кабачки, помидоры, шпинат, сливочный сыр, соевый соус, медовая горничная",
    price: 110000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Руколло с курицей и домашним сыром",
    description: "Rukkola, kurka, uy pishlog'i",
    price: 75000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥬",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Руколло с ростбифом",
    description: "Руккола, ростбиф, свежие огурцы, помидоры черри, пармезан, бальзамический уксус и крем",
    price: 130000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Баклажановые рулеты",
    description: "Baqlajon rulolari",
    price: 55000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🍆",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Хрустящие баклажаны",
    description: "Баклажаны, помидоры, кисло-сладкий соус, арахис, бальзамический крем",
    price: 65000,
    category: "cat_salads",
    categoryType: "food",
    emoji: "🍆",
    status: "active",
    popular: false,
    spicy: true,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 3. SHO'RVAlAR (SOUPS) ──────────────────────────────────────────────────
const soupItems = [
  {
    name: "Борщ",
    description: "350 гр. An'anaviy borsch",
    price: 40000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🥣",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Куриный суп с лапшой",
    description: "350 гр. Лапша, куриное филе",
    price: 25000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🍲",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Мастава",
    description: "350 гр. O'zbek mastava",
    price: 30000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🍲",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Сырный суп",
    description: "350 гр. Pishloqli sho'rva",
    price: 35000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🧀",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чечевичный крем суп",
    description: "300 гр. Yasmiq krem sho'rvasi",
    price: 25000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🥣",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лагман",
    description: "An'anaviy lag'man",
    price: 45000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🍜",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Том-ям из морепродуктов",
    description: "450 гр. Помидоры черри, шампиньоны, рыба судак, рыба Ласос, креветки",
    price: 120000,
    category: "cat_soups",
    categoryType: "food",
    emoji: "🦐",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 4. ITALYAN TAOMLARI ─────────────────────────────────────────────────────
const italianItems = [
  {
    name: "Альфредо",
    description: "350 гр. Спагетти, куриное филе, шампиньоны, сливки, сыр пармезан",
    price: 70000,
    category: "cat_italian",
    categoryType: "food",
    emoji: "🍝",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Болоньеза",
    description: "290 гр. Спагетти, говяжьий фарш, сыр пармезан",
    price: 55000,
    category: "cat_italian",
    categoryType: "food",
    emoji: "🍝",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Карбонаро",
    description: "350 гр. Фитучина, индейка, яйцо, сливки, сыр пармезан",
    price: 90000,
    category: "cat_italian",
    categoryType: "food",
    emoji: "🍝",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Паста с овощами и соусом песто",
    description: "290 гр. Спагетти, болгарский микс, помидоры, соус песто, сыр Пармезан",
    price: 55000,
    category: "cat_italian",
    categoryType: "food",
    emoji: "🍝",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
];

// ─── 5. PIZZA ────────────────────────────────────────────────────────────────
const pizzaItems = [
  {
    name: "Марсельеза",
    description: "Куриная грудка, шампиньоны, сыр моцарелла, сливочный соус",
    price: 90000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🍕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Казы Пицца острый",
    description: "470 гр. Казы, стручковый перец, сыр моцарелла, томатный соус",
    price: 120000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🌶️",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Мясная пицца",
    description: "Куриное филе, говядина, охотничьи колбаски, томаты, сыр моцарелла, томатный соус",
    price: 100000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🍕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Пеперони",
    description: "Колбаса салями, сыр моцарелла",
    price: 80000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🍕",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Цезарь пицца",
    description: "850 гр. Куриная грудка, салат айсберг, помидоры черри, сыр моцарелла, сыр пармезан, соус цезарь",
    price: 90000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🍕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "4 Сыра",
    description: "Сыр пармезан, сыр моцарелла, сыр творожный, сыр чеддер",
    price: 100000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🧀",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Маргарита",
    description: "Сыр моцарелла, помидор, оливковое масло",
    price: 80000,
    category: "cat_pizza",
    categoryType: "food",
    emoji: "🍕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: false,
    createdAt: today(),
  },
];

// ─── 6. STEYKLAR ─────────────────────────────────────────────────────────────
const steakItems = [
  {
    name: "Стейк с ананасом",
    description: "140 гр. Бон-филе, консервированные ананасы, соус демигляс",
    price: 160000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Классический стейк",
    description: "280 гр. Бон-филе, картофель по деревенски, соус перечный",
    price: 190000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Филе миньон",
    description: "210 гр. Бон-филе, овощи гриль, перечный соус",
    price: 190000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Стейк Куриный",
    description: "180 гр. Нежное куриное филе, картофель по деревенски, чесночный соус",
    price: 50000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🍗",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Рибай стейк",
    description: "Сочный рибай с мраморной текстурой, обжаренный до идеального хруста, с хулигански румяной картошкой по деревенски и остроумным перечным соусом",
    price: 210000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Тибон",
    description: "Тибон с овощами на гриле и перечным соусом. Эталон силы и изящества на одной кости: роскошный тибон, объединяющий бархатистое филе и ароматный стриплойн",
    price: 240000,
    category: "cat_steaks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 7. MANGAL (GRILL) ──────────────────────────────────────────────────────
const grillItems = [
  {
    name: "Dana Sarma Kebap",
    description: "Temporarily unavailable",
    price: 75000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🥙",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Napoleon",
    description: "Temporarily unavailable",
    price: 65000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🍖",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Fantezi Kebap",
    description: "Temporarily unavailable",
    price: 50000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🥙",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Молотый Шашлык",
    description: "Фарш",
    price: 30000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🍖",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Шашлык из вырезки",
    description: "Говяжей вырезки",
    price: 110000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Шашлык из куриных крыльев",
    description: "Tovuq qanotlaridan shashlik",
    price: 30000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🍗",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сибас",
    description: "Это блюдо выглядит эффектно, но при этом готовится просто и быстро — отличный выбор для полезного и вкусного ужина",
    price: 190000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🐟",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Дорадо",
    description: "Dorado balig'i",
    price: 160000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🐟",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "ЖАЗ БАРАНИНА",
    description: "200 гр. Qo'zichoq go'shti",
    price: 87000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🍖",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "ЖАЗ ГОВЯДИНА",
    description: "200 ГР. Mol go'shti",
    price: 87000,
    category: "cat_grill",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 8. SOUSLAR ──────────────────────────────────────────────────────────────
const sauceItems = [
  {
    name: "Кетчуп",
    description: "Ketchup sousi",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🧂",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Майонез",
    description: "Mayonez sousi",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🧂",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Соус Чили",
    description: "Chili sousi",
    price: 12000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🌶️",
    status: "active",
    popular: false,
    spicy: true,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сырный Соус",
    description: "Pishloqli sous",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🧀",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Соус Терияки",
    description: "Teryaki sousi",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🧂",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Соус Сладкий Чили",
    description: "Shirin chili sousi",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🌶️",
    status: "active",
    popular: false,
    spicy: true,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Барбекю Соус",
    description: "Barbekyu sousi",
    price: 15000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🔥",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Перец",
    description: "Murch",
    price: 6000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🌶️",
    status: "active",
    popular: false,
    spicy: true,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мёд",
    description: "Asal",
    price: 10000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🍯",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сливочное масло",
    description: "Sariyog'",
    price: 8000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🧈",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Оливковое Масло",
    description: "Zaytun moyi",
    price: 15000,
    category: "cat_sauces",
    categoryType: "food",
    emoji: "🫒",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 9. SOVUQ APPETITLAR ────────────────────────────────────────────────────
const coldSnackItems = [
  {
    name: "Сырная тарелка",
    description: "280 гр. Turli pishloqlar assortimenti",
    price: 90000,
    category: "cat_cold_snacks",
    categoryType: "food",
    emoji: "🧀",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мясная нарезка",
    description: "Go'shtli assortiment",
    price: 160000,
    category: "cat_cold_snacks",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Фруктовый ассорти",
    description: "Банан, ананас, яблоко, киви",
    price: 130000,
    category: "cat_cold_snacks",
    categoryType: "food",
    emoji: "🍎",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Миндаль",
    description: "Bodom",
    price: 35000,
    category: "cat_cold_snacks",
    categoryType: "food",
    emoji: "🥜",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Фисташки",
    description: "Pista",
    price: 45000,
    category: "cat_cold_snacks",
    categoryType: "food",
    emoji: "🥜",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 10. BUYURTMA TAOMLAR ──────────────────────────────────────────────────
const customItems = [
  {
    name: "МЯСНОЕ АССОРТИ НА МАНГАЛЕ (4 ПЕРСОНЫ)",
    description: "Баранина карейка, куриные крылышкы, жаз говядина, картошка деревенски, молотый шашлик, овощи грил, соус чесночный, соус томатный",
    price: 430000,
    category: "cat_custom",
    categoryType: "food",
    emoji: "🔥",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "МЯСНОЕ АССОРТИ НА МАНГАЛЕ (6 ПЕРСОН)",
    description: "Баранина карейка, куриные крылышкы, жаз говядина, картошка деревенски, молотый шашлик, овощи грил, соус чесночный, соус томатный",
    price: 660000,
    category: "cat_custom",
    categoryType: "food",
    emoji: "🔥",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: false,
    createdAt: today(),
  },
  {
    name: "Казан-Кебаб",
    description: "1 кг. Kazan kebab",
    price: 350000,
    category: "cat_custom",
    categoryType: "food",
    emoji: "🍲",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 11. TURK TAOMLARI ──────────────────────────────────────────────────────
const turkishItems = [
  {
    name: "Kaşarlı Köfte",
    description: "Temporarily unavailable - Pishloqli kofta",
    price: 78000,
    category: "cat_turkish",
    categoryType: "food",
    emoji: "🧆",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Beyti Sarma",
    description: "Temporarily unavailable - Beyti sarmasi",
    price: 70000,
    category: "cat_turkish",
    categoryType: "food",
    emoji: "🥙",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Peynirli Köfte",
    description: "Temporarily unavailable - Pishloqli kofta",
    price: 99000,
    category: "cat_turkish",
    categoryType: "food",
    emoji: "🧆",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Güveç Kavurma",
    description: "Temporarily unavailable - G'uvachda qovurma",
    price: 80000,
    category: "cat_turkish",
    categoryType: "food",
    emoji: "🍲",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 12. ISSIQ TAOMLAR ──────────────────────────────────────────────────────
const hotItems = [
  {
    name: "НЕМЕЦКИЕ КОЛБАСКИ КУРИНЫЕ",
    description: "250 ГР. Nemis tovuq kolbaskalari",
    price: 80000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🌭",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Куринное бедро BBQ",
    description: "Tovuq soni BBQ sousida",
    price: 45000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🍗",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Бифштекс",
    description: "310 гр. Говяжья котлета, картофельное пюре, соус демигляс, яйцо пашот",
    price: 65000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мясо с сельдереем",
    description: "400 гр. Говяжий вырезка, сельдерей, помидоры, чеснок, соус соя, рис",
    price: 90000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Картофель по домашнему",
    description: "400 гр. Говяжья вырезка, картофель, шампиньоны, сливки",
    price: 95000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🥔",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Бефстроганов",
    description: "400 гр. Говяжья вырезка, шампиньоны, сливки, пюре",
    price: 90000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Курица по тайски",
    description: "500 гр. Куриное филе, болгарский микс, сельдерей, помидоры, соевый соус, рис",
    price: 95000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🍗",
    status: "active",
    popular: false,
    spicy: true,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лосось с карамелью",
    description: "380 гр. Temporarily unavailable - Karamelli losos",
    price: 140000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🐟",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Язык в сливочно-грибном соусе",
    description: "330 гр. Язык говяжий, шампиньоны, сливки, руккола, помидоры черри",
    price: 110000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "👅",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Медальон в сливочно-грибном соусе",
    description: "450 гр. Говяжья вырезка, шампиньоны, сливки",
    price: 150000,
    category: "cat_hot",
    categoryType: "food",
    emoji: "🥩",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: false,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── ICHIMLIKLAR ─────────────────────────────────────────────────────────────

// ─── 13. KOFFE ───────────────────────────────────────────────────────────────
const coffeeItems = [
  {
    name: "Американо",
    description: "Klassik americano",
    price: 20000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "☕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Эспрессо",
    description: "Kuchli espresso",
    price: 15000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "☕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Капучино",
    description: "Klassik kapuchino (sirop qo'shish 5,000 so'm)",
    price: 26000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "☕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Горячая карамель с зефиром",
    description: "Temporarily unavailable - Karamelli issiq ichimlik",
    price: 25000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "🍬",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Горячий шоколад с маршмеллоу",
    description: "Temporarily unavailable - Zefirli issiq shokolad",
    price: 25000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "🍫",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Горячий какао",
    description: "Temporarily unavailable - Issiq kakao",
    price: 20000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "🍫",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Латте",
    description: "Klassik latte (sirop qo'shish 5,000 so'm)",
    price: 35000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "☕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Латте Blue Lagoon",
    description: "Blue Lagoon latte",
    price: 24000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "💙",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мятный латте",
    description: "Yalpizli latte",
    price: 23000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "🌿",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Раф-кофе",
    description: "Raf kofe (sirop qo'shish 5,000 so'm)",
    price: 35000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "☕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Айс-капучино",
    description: "Sovuq kapuchino (sirop qo'shish 5,000 so'm)",
    price: 35000,
    category: "cat_coffee",
    categoryType: "bar",
    emoji: "🧊",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 14. CHOY ────────────────────────────────────────────────────────────────
const teaItems = [
  {
    name: "Чай из облепиха и маракуйи",
    description: "Temporarily unavailable - Oblepixa va marakuyali choy",
    price: 45000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍵",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай облепиха",
    description: "Temporarily unavailable - Oblepixa choyi",
    price: 40000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍵",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай горячий цитрус",
    description: "Temporarily unavailable - Issiq sitrus choy",
    price: 35000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍊",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай амазония",
    description: "Yapon yashil choyi, tropik mevalar",
    price: 35000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🌿",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай из груши с жасмином",
    description: "Temporarily unavailable - Jasminli nok choyi",
    price: 30000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍐",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Малиновый чай",
    description: "Klassik malinali choy",
    price: 45000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍓",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай фруктовый микс",
    description: "Mevali choy assortimenti",
    price: 35000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍎",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Чай гринфилд",
    description: "Greenfield choyi",
    price: 6000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍵",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Соблазн черный",
    description: "Qora choy, ananas, qizil smorodina, goji",
    price: 10000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍵",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Манговый фреш",
    description: "Yashil choy, ananas, banan",
    price: 10000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🥭",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сокровища японии",
    description: "Yapon choylari assortimenti",
    price: 10000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🇯🇵",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Масала",
    description: "Hind masala choyi (ziravorlar bilan)",
    price: 10000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🧂",
    status: "active",
    popular: true,
    spicy: true,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Манговый улун-зеленый",
    description: "Mango yashil choyi",
    price: 10000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🥭",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Навват",
    description: "Navvot (shirinlik)",
    price: 5000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍬",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимон",
    description: "Limon",
    price: 6000,
    category: "cat_tea",
    categoryType: "bar",
    emoji: "🍋",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 15. LIMONADLAR ──────────────────────────────────────────────────────────
const lemonadeItems = [
  {
    name: "Лимонад Кокос",
    description: "Kokos limonadi",
    price: 55000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🥥",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Грейпфрут",
    description: "Temporarily unavailable - Greyfruit limonadi",
    price: 55000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🍊",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Лимон-Мята",
    description: "Limon-yalpiz limonadi",
    price: 45000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🍋",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Манго-Маракуя",
    description: "Mango-marakuyali limonad",
    price: 50000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🥭",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Мандариновый",
    description: "Temporarily unavailable - Mandarin limonadi",
    price: 50000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🍊",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Топический",
    description: "Tropik limonad",
    price: 55000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🌴",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Лимонад Огуречно-Базиличный",
    description: "Temporarily unavailable - Bodring-bazilik limonadi",
    price: 50000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🥒",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Мохито Клубничный",
    description: "Temporarily unavailable - Qulupnayli mohito",
    price: 50000,
    category: "cat_lemonade",
    categoryType: "bar",
    emoji: "🍓",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 16. KOKTEYLLAR ──────────────────────────────────────────────────────────
const cocktailItems = [
  {
    name: "Малина грейфрут",
    description: "Malina greyfruit kokteyli (300 ml)",
    price: 50000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍹",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Пина колада",
    description: "Pina colada (300 ml)",
    price: 39999,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍍",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Леденая амазония",
    description: "Muzli amazoniya (300 ml)",
    price: 39999,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🧊",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Дикая малина",
    description: "Yovvoyi malina (300 ml)",
    price: 38000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍓",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Экстро колада",
    description: "Extra colada (300 ml)",
    price: 40000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍹",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Кокос алое",
    description: "Kokos aloe (300 ml)",
    price: 45000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🥥",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Солначный цитрус",
    description: "Quyoshli sitrus (300 ml)",
    price: 40000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "☀️",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "МАРАКУЙЯ КАРАМЕЛЬ",
    description: "300 МЛ. Marakuya karamel",
    price: 40000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍯",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "ОРЕНЖ ПАРАДАЙС",
    description: "300 МЛ. Orange paradise",
    price: 20000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🍊",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Киви тропикал",
    description: "300 мл. Kiwi tropical",
    price: 30000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🥝",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Наслаждение",
    description: "300 мл. Zavq",
    price: 20000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "😊",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Берлин",
    description: "300 мл. Berlin",
    price: 25000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🇩🇪",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Малина миндаль",
    description: "300 мл. Malina bodom",
    price: 25000,
    category: "cat_cocktails",
    categoryType: "bar",
    emoji: "🥜",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 17. MILK-SHKEYKLAR ──────────────────────────────────────────────────────
const milkshakeItems = [
  {
    name: "Шоколадный милкшейк",
    description: "Shokoladli milk-shkeyk",
    price: 30000,
    category: "cat_milkshake",
    categoryType: "bar",
    emoji: "🍫",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Банановый милкшейк",
    description: "Bananli milk-shkeyk",
    price: 30000,
    category: "cat_milkshake",
    categoryType: "bar",
    emoji: "🍌",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Клубничный милкшейк",
    description: "Qulupnayli milk-shkeyk",
    price: 30000,
    category: "cat_milkshake",
    categoryType: "bar",
    emoji: "🍓",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Малиновый милкшейк",
    description: "Malinali milk-shkeyk",
    price: 30000,
    category: "cat_milkshake",
    categoryType: "bar",
    emoji: "🍓",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сникерс милкшейк",
    description: "Snickers milk-shkeyk",
    price: 30000,
    category: "cat_milkshake",
    categoryType: "bar",
    emoji: "🍫",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 18. FRESH VA SMOOTHIE ──────────────────────────────────────────────────
const freshItems = [
  {
    name: "Морковный фреш",
    description: "Sabzili fresh",
    price: 20000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🥕",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Яблочный фреш",
    description: "Olma fresh",
    price: 20000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍎",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Апельсиновый фреш",
    description: "Apelsin fresh",
    price: 20000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍊",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Витаминный смузи",
    description: "Vitaminli smoozi",
    price: 35000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🧃",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи творожно-Банановый",
    description: "Tvorog-bananli smoozi",
    price: 35000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍌",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи из Банана и Киви",
    description: "Banan va kivi smoozi",
    price: 45000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🥝",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи из яблоко и банана",
    description: "Olma va banan smoozi",
    price: 35000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍎",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи из малины и банана",
    description: "Malina va banan smoozi",
    price: 35000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍓",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи ASMALD",
    description: "ASMALD maxsus smoozi",
    price: 38000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🌟",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Смузи из персика и малины",
    description: "Temporarily unavailable - Shaftoli va malina",
    price: 45000,
    category: "cat_fresh",
    categoryType: "bar",
    emoji: "🍑",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── 19. SOVUQ ICHIMLIKLAR ──────────────────────────────────────────────────
const coldDrinkItems = [
  {
    name: "Coca-Cola 1L",
    description: "Coca-Cola 1 litr",
    price: 17000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Coca-Cola 0.5L",
    description: "Coca-Cola 0.5 litr",
    price: 9000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Fanta 1L",
    description: "Fanta 1 litr",
    price: 17000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Fanta 0.5L",
    description: "Fanta 0.5 litr",
    price: 9000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Pepsi 1L",
    description: "Pepsi 1 litr",
    price: 17000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Pepsi 0.5L",
    description: "Pepsi 0.5 litr",
    price: 9000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🥤",
    status: "active",
    popular: true,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сок Блисс",
    description: "Temporarily unavailable - Bliss sharbati",
    price: 18000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🧃",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Сок Дена",
    description: "Dena sharbati",
    price: 20000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🧃",
    status: "active",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
  {
    name: "Детский Сок",
    description: "Temporarily unavailable - Bolalar sharbati",
    price: 10000,
    category: "cat_cold_drinks",
    categoryType: "bar",
    emoji: "🧃",
    status: "stop",
    popular: false,
    spicy: false,
    vegetarian: true,
    glutenFree: true,
    createdAt: today(),
  },
];

// ─── BARCHA MAHSULOTLARNI BIRLASHTIRISH ──────────────────────────────────
const allItems = [
  ...breadItems,
  ...saladItems,
  ...soupItems,
  ...italianItems,
  ...pizzaItems,
  ...steakItems,
  ...grillItems,
  ...sauceItems,
  ...coldSnackItems,
  ...customItems,
  ...turkishItems,
  ...hotItems,
  ...coffeeItems,
  ...teaItems,
  ...lemonadeItems,
  ...cocktailItems,
  ...milkshakeItems,
  ...freshItems,
  ...coldDrinkItems,
];

// ─── FIREBASE GA YUKLASH ──────────────────────────────────────────────────
export async function seedMenuData() {
  console.log("🌿 AMAZONIA MENU MA'LUMOTLARI YUKLANMOQDA...");
  console.log("========================================");

  try {
    // ── 1. KATEGORIYALARNI YUKLASH ──
    console.log("\n📁 Kategoriyalar yuklanmoqda...");
    for (const [key, cat] of Object.entries(CATEGORIES)) {
      await dbSet(`categories/${cat.id}`, {
        name: cat.name,
        icon: cat.icon,
        color: cat.color,
        status: cat.status,
        createdAt: cat.createdAt,
      });
      console.log(`✅ ${cat.name} kategoriyasi yuklandi`);
    }

    // ── 2. MAHSULOTLARNI YUKLASH ──
    console.log("\n🍽️ Mahsulotlar yuklanmoqda...");
    let count = 0;
    for (const item of allItems) {
      const id = `menu_${uid()}`;
      await dbSet(`menu/${id}`, {
        ...item,
        id: id,
      });
      count++;
      console.log(`✅ ${count}. ${item.name} — ${item.price.toLocaleString()} so'm`);
    }

    console.log("\n========================================");
    console.log(`✅ JAMI ${count} ta mahsulot yuklandi!`);
    console.log(`✅ ${Object.keys(CATEGORIES).length} ta kategoriya yuklandi!`);
    console.log("🌿 AMAZONIA MENU TAYYOR!");

    return { success: true, categories: Object.keys(CATEGORIES).length, items: count };
  } catch (error) {
    console.error("❌ XATOLIK:", error);
    return { success: false, error: error.message };
  }
}

export default seedMenuData;